
docker_build('lucianoarendt/todo-list-app',
            context='../backend')

k8s_yaml(['mysql-todo-list-app-configmap.yaml', 
        'todo-list-app-configmap.yaml',
        'mysql-todo-list-app-pvc.yaml',
        'mysql-todo-list-app-deployment.yaml',
        'redis-todo-list-app-deployment.yaml',
        'todo-list-app-deployment.yaml',
        'mysql-todo-list-app-svc.yaml',
        'redis-todo-list-app-svc.yaml',
        'todo-list-app-svc.yaml',
        ])
