version: '3'
services:
  db:
    container_name: mysql-todo-list-app
    image: 'mysql:5.7'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=root
      - DATABASE_HOST=db
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql

  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - cache:/data
volumes:
  cache: